export const ENUMERATION_CATEGORIES = [
  'race-archetype',
  'animal-type',
  'creature-lore',
  'historic-lore',
  'material-lore',
  'spell-lore',
  'environment',
  'vehicle',
  'region',
  'religion',
  'melee-weapon-type',
  'ranged-weapon-type',
  'skill-combat-training',
  'spell-list',
  'skill-directed-spell',
  'skill-culinary',
  'skill-fabric-craft',
  'skill-administration',
  'skill-trade',
  'skill-service',
  'skill-mechanics',
  'skill-leathercraft',
  'skill-metalcraft',
  'skill-stonecraft',
  'skill-woodcraft',
  'skill-influence',
  'skill-music',
  'skill-magic-ritual',
] as const;

export type EnumerationCategory = (typeof ENUMERATION_CATEGORIES)[number];
