import { Profession } from '../../domain/entities/profession.entity';

export const PROFESSIONS: Profession[] = [
  {
    id: 'rogue',
    skillCosts: {
      animal: [2, 4],
      awareness: [2, 3],
      'battle-expertise': [3, 4],
      'body-discipline': [4, 6],
      brawn: [2, 4],
      'combat-expertise': [3, 4],
      combat1: [1, 3],
      combat2: [2, 3],
      combat3: [3, 4],
      combat4: [4, 6],
      composition: [3, 4],
      crafting: [2, 4],
      delving: [7, 10],
      environmental: [2, 4],
      gymnastic: [2, 3],
      lore: [2, 4],
      'magical-expertise': [7, 10],
      medical: [3, 4],
      'mental-discipline': [5, 7],
      movement: [1, 3],
      'performance-art': [2, 4],
      'power-manipulation': [9, 12],
      science: [5, 7],
      social: [2, 3],
      'spells-base-open': [7, 10],
      'spells-ritual-magic': [9, 12],
      'spells-closed': [15, 20],
      'spells-arcane': [15, 20],
      'spells-restricted': [15, 20],
      subterfuge: [1, 3],
      technical: [2, 3],
      vocation: [3, 4],
    },
    professionalSkills: [
      'riding',
      'perception',
      'body-development',
      'armor-maneuver',
      'restricted-quarters',
      'blind-fighting',
      'melee-weapons',
      'ranged-weapons',
      'survival',
      'jumping',
      'poison-mastery',
      'climbing',
      'running',
      'ambush',
      'stealth',
    ],
  },
  {
    id: 'fighter',
    skillCosts: {
      animal: [2, 3],
      awareness: [2, 4],
      'battle-expertise': [1, 2],
      'body-discipline': [4, 6],
      brawn: [1, 3],
      'combat-expertise': [1, 3],
      combat1: [1, 2],
      combat2: [1, 2],
      combat3: [2, 3],
      combat4: [3, 4],
      composition: [3, 4],
      crafting: [2, 4],
      delving: [7, 10],
      environmental: [2, 4],
      gymnastic: [3, 4],
      lore: [2, 4],
      'magical-expertise': [7, 10],
      medical: [3, 4],
      'mental-discipline': [5, 7],
      movement: [2, 4],
      'performance-art': [3, 4],
      'power-manipulation': [9, 12],
      science: [5, 7],
      social: [2, 4],
      'spells-base-open': [7, 10],
      'spells-ritual-magic': [9, 12],
      'spells-closed': [15, 20],
      'spells-arcane': [15, 20],
      'spells-restricted': [15, 20],
      subterfuge: [3, 5],
      technical: [5, 7],
      vocation: [3, 4],
    },
    professionalSkills: [
      'riding',
      'body-development',
      'fortitude',
      'weight-training',
      'armor-maneuver',
      'mounted-combat',
      'protect',
      'disarm',
      'multiple-attacks',
      'melee-weapons',
      'ranged-weapons',
      'shield',
      'metalcraft',
      'running',
      'leadership',
    ],
  },
  {
    id: 'ranger',
    skillCosts: {
      animal: [1, 3],
      awareness: [1, 3],
      'battle-expertise': [4, 6],
      'body-discipline': [6, 8],
      brawn: [4, 6],
      'combat-expertise': [3, 5],
      combat1: [3, 4],
      combat2: [3, 5],
      combat3: [5, 7],
      combat4: [7, 10],
      composition: [3, 4],
      crafting: [2, 4],
      delving: [6, 8],
      environmental: [1, 3],
      gymnastic: [3, 4],
      lore: [2, 4],
      'magical-expertise': [6, 8],
      medical: [3, 5],
      'mental-discipline': [5, 7],
      movement: [1, 3],
      'performance-art': [3, 4],
      'power-manipulation': [4, 6],
      science: [5, 7],
      social: [3, 4],
      'spells-base-open': [3, 4],
      'spells-ritual-magic': [3, 5],
      'spells-closed': [5, 7],
      'spells-arcane': [12, 15],
      'spells-restricted': [15, 20],
      subterfuge: [2, 4],
      technical: [5, 7],
      vocation: [3, 4],
    },
    professionalSkills: [
      'animal-handling',
      'riding',
      'perception',
      'tracking',
      'melee-weapons',
      'ranged-weapons',
      'navigation',
      'survival',
      'creature-lore',
      'region-lore',
      'climbing',
      'running',
      'swimming',
      'concealment',
      'stalking',
    ],
  },
];
