import { Profession } from '../../domain/entities/profession.entity';

export const PROFESSIONS: Profession[] = [
  {
    id: 'rogue',
    skillCosts: {
      animal: [2, 4],
      awareness: [2, 3],
      battleExpertise: [3, 4],
      bodyDiscipline: [4, 6],
      brawn: [2, 4],
      combatExpertise: [3, 4],
      combat1: [1, 3],
      combat2: [2, 3],
      combat3: [3, 4],
      combat4: [4, 6],
      composition: [3, 4],
      crafting: [2, 4],
      delving: [7, 10],
      environmental: [2, 4],
      gymnastic: [2, 3],
      lore: [2, 4],
      magicalExpertise: [7, 10],
      medical: [3, 4],
      mentalDiscipline: [5, 7],
      movement: [1, 3],
      performanceArt: [2, 4],
      powerManipulation: [9, 12],
      science: [5, 7],
      social: [2, 3],
      spellsBaseOpen: [7, 10],
      spellsRitualMagic: [9, 12],
      spellsClosed: [15, 20],
      spellsArcane: [15, 20],
      spellsRestricted: [15, 20],
      subterfuge: [1, 3],
      technical: [2, 3],
      vocation: [3, 4],
    },
    professionalSkills: [
      'riding',
      'perception',
      'body-development',
      'armor-maneuver',
      'restricted-quarters',
      'blind-fighting',
      'melee-weapons',
      'ranged-weapons',
      'survival',
      'jumping',
      'poison-mastery',
      'climbing',
      'running',
      'ambush',
      'stealth',
    ],
  },
];
