import { injectable, inject } from 'inversify';
import { TYPES } from '@shared/types/container';
import { ArmorTypeRepository } from '@domain/ports/ArmorTypeRepository';
import { ArmorType, ArmorTypeCreateRequest, ArmorTypeUpdateRequest } from '@domain/entities/ArmorType';
import { NotFoundError } from '@shared/errors';

@injectable()
export class ArmorTypeService {
  constructor(
    @inject(TYPES.ArmorTypeRepository) private armorTypeRepository: ArmorTypeRepository
  ) {}

  async findById(id: number): Promise<ArmorType> {
    const armorType = await this.armorTypeRepository.findById(id);
    if (!armorType) {
      throw new NotFoundError(`Armor type with id ${id} not found`);
    }
    return armorType;
  }

  async findAll(): Promise<ArmorType[]> {
    return await this.armorTypeRepository.findAll();
  }

  async create(request: ArmorTypeCreateRequest): Promise<ArmorType> {
    const armorType: ArmorType = {
      id: 0, // Will be generated by repository
      name: request.name
    };

    return await this.armorTypeRepository.create(armorType);
  }

  async update(id: number, request: ArmorTypeUpdateRequest): Promise<ArmorType> {
    const existingArmorType = await this.armorTypeRepository.findById(id);
    if (!existingArmorType) {
      throw new NotFoundError(`Armor type with id ${id} not found`);
    }

    const updatedArmorType = await this.armorTypeRepository.update(id, request);
    if (!updatedArmorType) {
      throw new NotFoundError(`Armor type with id ${id} not found`);
    }

    return updatedArmorType;
  }

  async deleteById(id: number): Promise<void> {
    const armorType = await this.armorTypeRepository.findById(id);
    if (!armorType) {
      throw new NotFoundError(`Armor type with id ${id} not found`);
    }

    const deleted = await this.armorTypeRepository.deleteById(id);
    if (!deleted) {
      throw new NotFoundError(`Armor type with id ${id} not found`);
    }
  }
}
